/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package archive;

import java.awt.ComponentOrientation;
import java.awt.Desktop;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URISyntaxException;
import java.net.URL;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Mohammed
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
       
    private DataBaseManger data;
    private int Authorize;

    
    public home(DataBaseManger data , int authorize) {
        initComponents();
        
        this.data = data;
        this.Authorize = authorize;

       DefaultTableModel model = new DefaultTableModel() {

    @Override
    public boolean isCellEditable(int row, int column) {
       //all cells false
       return false;
    }
}; 
         EmpTable.setModel(model);

        // Create a couple of columns 
        model.addColumn("PHONE");
        model.addColumn("ID");
        model.addColumn("NAME"); 
          
        for (int i = 0; i < data.getSize(); i++) {
        // Append a row 
        model.addRow(new Object[]{data.getinfo(i).getPhone(), data.getinfo(i).getID() , data.getinfo(i).getName()});

        }

        for(int i = 0; i< EmpTable.getColumnCount(); i++){
            
                    
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(SwingConstants.RIGHT);
        EmpTable.getColumnModel().getColumn(i).setCellRenderer(rightRenderer);
        }
        
        
        DefaultTableCellRenderer renderer = (DefaultTableCellRenderer) EmpTable.getTableHeader().getDefaultRenderer();
        renderer.setHorizontalAlignment(0);
        
        
        
        DefaultTableModel Emodel = new DefaultTableModel() {

       @Override
       public boolean isCellEditable(int row, int column) {
          //all cells false
          return false;
          }
             }; 
         ExpensesTable.setModel(Emodel);

        // Create a couple of columns 
        Emodel.addColumn("الشركة ");
        Emodel.addColumn("الاسم"); 
        
        for (int i = 0; i < data.getExpSize(); i++) {
        Emodel.addRow(new Object[] {data.getExp(i).getCompany() , data.getExp(i).getName()});
        

                }
        
        
        renderer = (DefaultTableCellRenderer) ExpensesTable.getTableHeader().getDefaultRenderer();
        renderer.setHorizontalAlignment(0);
        
                for(int i = 0; i < 2; i++){
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(SwingConstants.RIGHT);
        ExpensesTable.getColumnModel().getColumn(i).setCellRenderer(rightRenderer);
            
        }
        

    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nav1 = new javax.swing.JPanel();
        home = new javax.swing.JButton();
        employee = new javax.swing.JButton();
        expenses = new javax.swing.JButton();
        progz = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        nav2 = new javax.swing.JPanel();
        navHome1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        navExpensesH1 = new javax.swing.JPanel();
        navExpansesH = new javax.swing.JPanel();
        navEmpHead = new javax.swing.JLabel();
        ExpAdd1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        ExpensesTable = new javax.swing.JTable();
        navEmployeeH = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        EmpAdd = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        EmpTable = new javax.swing.JTable();
        navProgz = new javax.swing.JPanel();
        farsbutton = new javax.swing.JButton();
        moebutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        norbutton = new javax.swing.JButton();
        navEmployeeAdd = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        NummberE = new javax.swing.JTextField();
        NameE = new javax.swing.JTextField();
        EmailE = new javax.swing.JTextField();
        MissionE = new javax.swing.JTextField();
        ExecE = new javax.swing.JTextField();
        PerfE = new javax.swing.JTextField();
        RegiE = new javax.swing.JTextField();
        SaveEmp = new javax.swing.JButton();
        cancelEmp = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        Password = new javax.swing.JTextField();
        navEmployee = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        EmpInfo = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        cancelExp4 = new javax.swing.JButton();
        navExpensesِAdd = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        Count = new javax.swing.JLabel();
        Model = new javax.swing.JLabel();
        SerNum = new javax.swing.JLabel();
        CompN = new javax.swing.JLabel();
        other = new javax.swing.JLabel();
        SerNum2 = new javax.swing.JTextField();
        Count2 = new javax.swing.JTextField();
        CompN2 = new javax.swing.JTextField();
        MissionE2 = new javax.swing.JTextField();
        Model2 = new javax.swing.JTextField();
        SaveExp2 = new javax.swing.JButton();
        cancelExp2 = new javax.swing.JButton();
        Name = new javax.swing.JLabel();
        Name2 = new javax.swing.JTextField();
        navExpensesِ = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ExpShow = new javax.swing.JTable();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        cancelExp3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        nav1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        home.setBackground(new java.awt.Color(102, 204, 255));
        home.setFont(new java.awt.Font("AdvertisingBold", 0, 11)); // NOI18N
        home.setText("الرئيسية");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        employee.setBackground(new java.awt.Color(102, 204, 255));
        employee.setFont(new java.awt.Font("AdvertisingBold", 0, 11)); // NOI18N
        employee.setText("الموظفين");
        employee.setMaximumSize(new java.awt.Dimension(73, 23));
        employee.setMinimumSize(new java.awt.Dimension(73, 23));
        employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeActionPerformed(evt);
            }
        });

        expenses.setBackground(new java.awt.Color(102, 204, 255));
        expenses.setFont(new java.awt.Font("AdvertisingBold", 0, 11)); // NOI18N
        expenses.setText("مصروفات القسم");
        expenses.setMaximumSize(new java.awt.Dimension(73, 23));
        expenses.setMinimumSize(new java.awt.Dimension(73, 23));
        expenses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expensesActionPerformed(evt);
            }
        });

        progz.setBackground(new java.awt.Color(102, 204, 255));
        progz.setFont(new java.awt.Font("AdvertisingBold", 0, 11)); // NOI18N
        progz.setText("البرامج الخاصة بالقسم");
        progz.setMaximumSize(new java.awt.Dimension(73, 23));
        progz.setMinimumSize(new java.awt.Dimension(73, 23));
        progz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                progzActionPerformed(evt);
            }
        });

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archive/logo.png"))); // NOI18N

        jLabel32.setBackground(new java.awt.Color(51, 51, 51));
        jLabel32.setFont(new java.awt.Font("AdvertisingBold", 0, 10)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText(" تنفيذ وبرمجة: نايف محسن , محمد هندي ");
        jLabel32.setOpaque(true);

        javax.swing.GroupLayout nav1Layout = new javax.swing.GroupLayout(nav1);
        nav1.setLayout(nav1Layout);
        nav1Layout.setHorizontalGroup(
            nav1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nav1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nav1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(progz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(expenses, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(employee, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        nav1Layout.setVerticalGroup(
            nav1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nav1Layout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(employee, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(expenses, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(progz, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel32))
        );

        nav2.setBackground(new java.awt.Color(255, 255, 255));
        nav2.setLayout(new java.awt.CardLayout());

        navHome1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archive/home.jpg"))); // NOI18N

        javax.swing.GroupLayout navHome1Layout = new javax.swing.GroupLayout(navHome1);
        navHome1.setLayout(navHome1Layout);
        navHome1Layout.setHorizontalGroup(
            navHome1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        navHome1Layout.setVerticalGroup(
            navHome1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        nav2.add(navHome1, "card2");

        navExpensesH1.setBackground(new java.awt.Color(255, 255, 255));

        navExpansesH.setBackground(new java.awt.Color(255, 255, 255));

        navEmpHead.setFont(new java.awt.Font("AdvertisingBold", 0, 14)); // NOI18N
        navEmpHead.setText("مصروفات القسم");

        ExpAdd1.setBackground(new java.awt.Color(102, 204, 255));
        ExpAdd1.setFont(new java.awt.Font("AdvertisingBold", 0, 10)); // NOI18N
        ExpAdd1.setText("اضافة جديد");
        ExpAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpAdd1ActionPerformed(evt);
            }
        });

        ExpensesTable.setFont(new java.awt.Font("AdvertisingBold", 0, 12)); // NOI18N
        ExpensesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        ExpensesTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExpensesTableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(ExpensesTable);

        javax.swing.GroupLayout navExpansesHLayout = new javax.swing.GroupLayout(navExpansesH);
        navExpansesH.setLayout(navExpansesHLayout);
        navExpansesHLayout.setHorizontalGroup(
            navExpansesHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navExpansesHLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(navExpansesHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navExpansesHLayout.createSequentialGroup()
                        .addComponent(ExpAdd1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navExpansesHLayout.createSequentialGroup()
                        .addComponent(navEmpHead)
                        .addGap(143, 143, 143))))
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
        );
        navExpansesHLayout.setVerticalGroup(
            navExpansesHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navExpansesHLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(navEmpHead)
                .addGap(18, 18, 18)
                .addComponent(ExpAdd1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout navExpensesH1Layout = new javax.swing.GroupLayout(navExpensesH1);
        navExpensesH1.setLayout(navExpensesH1Layout);
        navExpensesH1Layout.setHorizontalGroup(
            navExpensesH1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 674, Short.MAX_VALUE)
            .addGroup(navExpensesH1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(navExpensesH1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(navExpansesH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        navExpensesH1Layout.setVerticalGroup(
            navExpensesH1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 664, Short.MAX_VALUE)
            .addGroup(navExpensesH1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(navExpensesH1Layout.createSequentialGroup()
                    .addComponent(navExpansesH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        nav2.add(navExpensesH1, "card2");

        navEmployeeH.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("AdvertisingBold", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("موظفين القسم");

        EmpAdd.setBackground(new java.awt.Color(102, 204, 255));
        EmpAdd.setFont(new java.awt.Font("AdvertisingBold", 0, 10)); // NOI18N
        EmpAdd.setText("إضافة موظف");
        EmpAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpAddActionPerformed(evt);
            }
        });

        EmpTable.setFont(new java.awt.Font("AdvertisingBold", 0, 12)); // NOI18N
        EmpTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, ""},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        EmpTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmpTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(EmpTable);

        javax.swing.GroupLayout navEmployeeHLayout = new javax.swing.GroupLayout(navEmployeeH);
        navEmployeeH.setLayout(navEmployeeHLayout);
        navEmployeeHLayout.setHorizontalGroup(
            navEmployeeHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navEmployeeHLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(navEmployeeHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(navEmployeeHLayout.createSequentialGroup()
                        .addGap(0, 567, Short.MAX_VALUE)
                        .addComponent(EmpAdd))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navEmployeeHLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(293, 293, 293))
        );
        navEmployeeHLayout.setVerticalGroup(
            navEmployeeHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navEmployeeHLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmpAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
                .addContainerGap())
        );

        nav2.add(navEmployeeH, "card2");

        navProgz.setBackground(new java.awt.Color(255, 255, 255));

        farsbutton.setBackground(new java.awt.Color(102, 204, 255));
        farsbutton.setText("فتح في المتصفح");
        farsbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                farsbuttonActionPerformed(evt);
            }
        });

        moebutton.setBackground(new java.awt.Color(102, 204, 255));
        moebutton.setText("فتح في المتصفح");
        moebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moebuttonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("AdvertisingBold", 0, 12)); // NOI18N
        jLabel1.setText("نظام نور");

        jLabel2.setFont(new java.awt.Font("AdvertisingBold", 0, 12)); // NOI18N
        jLabel2.setText("نظام فارس");

        jLabel3.setFont(new java.awt.Font("AdvertisingBold", 0, 14)); // NOI18N
        jLabel3.setText("البرامج الخاصة بقسم تقنية المعلومات");

        jLabel6.setFont(new java.awt.Font("AdvertisingBold", 0, 12)); // NOI18N
        jLabel6.setText("بوابة الوزارة");

        norbutton.setBackground(new java.awt.Color(102, 204, 255));
        norbutton.setText("فتح في المتصفح");
        norbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                norbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navProgzLayout = new javax.swing.GroupLayout(navProgz);
        navProgz.setLayout(navProgzLayout);
        navProgzLayout.setHorizontalGroup(
            navProgzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navProgzLayout.createSequentialGroup()
                .addContainerGap(383, Short.MAX_VALUE)
                .addGroup(navProgzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navProgzLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(77, 77, 77))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navProgzLayout.createSequentialGroup()
                        .addGroup(navProgzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(moebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(norbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(farsbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(navProgzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(78, 78, 78))))
        );
        navProgzLayout.setVerticalGroup(
            navProgzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navProgzLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel3)
                .addGap(25, 25, 25)
                .addGroup(navProgzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(moebutton))
                .addGap(9, 9, 9)
                .addGroup(navProgzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(norbutton))
                .addGap(9, 9, 9)
                .addGroup(navProgzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(farsbutton))
                .addContainerGap(460, Short.MAX_VALUE))
        );

        nav2.add(navProgz, "card2");

        navEmployeeAdd.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("AdvertisingBold", 0, 14)); // NOI18N
        jLabel11.setText("إضافة موظف");

        jLabel12.setFont(new java.awt.Font("AdvertisingBold", 0, 12)); // NOI18N
        jLabel12.setText("الاسم ");

        jLabel13.setFont(new java.awt.Font("AdvertisingBold", 0, 12)); // NOI18N
        jLabel13.setText("السجل المدني");

        jLabel14.setFont(new java.awt.Font("AdvertisingBold", 0, 12)); // NOI18N
        jLabel14.setText("رقم الجوال");

        jLabel15.setFont(new java.awt.Font("AdvertisingBold", 0, 12)); // NOI18N
        jLabel15.setText("البريد الالكتروني");

        jLabel16.setFont(new java.awt.Font("AdvertisingBold", 0, 12)); // NOI18N
        jLabel16.setText("المهمة في القسم");

        jLabel17.setFont(new java.awt.Font("AdvertisingBold", 0, 12)); // NOI18N
        jLabel17.setText("المسمى الوظيفي");

        jLabel18.setFont(new java.awt.Font("AdvertisingBold", 0, 12)); // NOI18N
        jLabel18.setText("نسبة انجاز العمل");

        NameE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameEActionPerformed(evt);
            }
        });

        SaveEmp.setBackground(new java.awt.Color(102, 204, 255));
        SaveEmp.setFont(new java.awt.Font("AdvertisingBold", 0, 11)); // NOI18N
        SaveEmp.setText("حفظ");
        SaveEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveEmpActionPerformed(evt);
            }
        });

        cancelEmp.setBackground(new java.awt.Color(102, 204, 255));
        cancelEmp.setFont(new java.awt.Font("AdvertisingBold", 0, 11)); // NOI18N
        cancelEmp.setText("الغاء");
        cancelEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelEmpActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("AdvertisingBold", 0, 12)); // NOI18N
        jLabel22.setText("     كلمة المرور");

        javax.swing.GroupLayout navEmployeeAddLayout = new javax.swing.GroupLayout(navEmployeeAdd);
        navEmployeeAdd.setLayout(navEmployeeAddLayout);
        navEmployeeAddLayout.setHorizontalGroup(
            navEmployeeAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navEmployeeAddLayout.createSequentialGroup()
                .addContainerGap(373, Short.MAX_VALUE)
                .addGroup(navEmployeeAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navEmployeeAddLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(145, 145, 145))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navEmployeeAddLayout.createSequentialGroup()
                        .addComponent(cancelEmp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SaveEmp)
                        .addGap(136, 136, 136))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navEmployeeAddLayout.createSequentialGroup()
                        .addGroup(navEmployeeAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(navEmployeeAddLayout.createSequentialGroup()
                                .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(navEmployeeAddLayout.createSequentialGroup()
                                .addGroup(navEmployeeAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(NummberE, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ExecE, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PerfE, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MissionE, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EmailE, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NameE, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RegiE, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(navEmployeeAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18))))
                        .addGap(25, 25, 25))))
        );
        navEmployeeAddLayout.setVerticalGroup(
            navEmployeeAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navEmployeeAddLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(navEmployeeAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(NameE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(navEmployeeAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(RegiE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(navEmployeeAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(NummberE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(navEmployeeAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(EmailE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(navEmployeeAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(MissionE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(navEmployeeAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(PerfE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(navEmployeeAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(ExecE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(navEmployeeAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(navEmployeeAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveEmp)
                    .addComponent(cancelEmp))
                .addContainerGap(263, Short.MAX_VALUE))
        );

        nav2.add(navEmployeeAdd, "card2");

        navEmployee.setBackground(new java.awt.Color(255, 255, 255));

        EmpInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EmpInfo.setFont(new java.awt.Font("AdvertisingBold", 0, 12)); // NOI18N
        EmpInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "الاسم"},
                {null, "السجل المدني"},
                {null, "رقم الجوال"},
                {null, "البريد الالكتروني"},
                {null, "المهمه في القسم"},
                {null, "الاداء الوظيفي"},
                {null, "نسبة انجاز العمل"}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        EmpInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(EmpInfo);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archive/logo.png"))); // NOI18N

        jLabel20.setFont(new java.awt.Font("AdvertisingBold", 0, 12)); // NOI18N
        jLabel20.setText("ادارة التعليم بمحافظة عفيف - قسم تقنية المعلومات");

        jLabel21.setFont(new java.awt.Font("AdvertisingBold", 0, 11)); // NOI18N
        jLabel21.setText("إستعلام عن موظف بالقسم");

        jButton3.setBackground(new java.awt.Color(102, 204, 255));
        jButton3.setFont(new java.awt.Font("AdvertisingBold", 0, 11)); // NOI18N
        jButton3.setText("طباعة");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        cancelExp4.setBackground(new java.awt.Color(102, 204, 255));
        cancelExp4.setFont(new java.awt.Font("AdvertisingBold", 0, 11)); // NOI18N
        cancelExp4.setText("رجوع");
        cancelExp4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelExp4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navEmployeeLayout = new javax.swing.GroupLayout(navEmployee);
        navEmployee.setLayout(navEmployeeLayout);
        navEmployeeLayout.setHorizontalGroup(
            navEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navEmployeeLayout.createSequentialGroup()
                .addGap(0, 412, Short.MAX_VALUE)
                .addGroup(navEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navEmployeeLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(78, 78, 78))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navEmployeeLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(146, 146, 146))))
            .addGroup(navEmployeeLayout.createSequentialGroup()
                .addGroup(navEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navEmployeeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(navEmployeeLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel19)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(navEmployeeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelExp4)))
                .addContainerGap())
        );
        navEmployeeLayout.setVerticalGroup(
            navEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navEmployeeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(navEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(cancelExp4))
                .addGap(257, 257, 257))
        );

        nav2.add(navEmployee, "card2");

        navExpensesِAdd.setBackground(new java.awt.Color(255, 255, 255));

        title.setFont(new java.awt.Font("AdvertisingBold", 0, 14)); // NOI18N
        title.setText("اضافة مصروفات");

        Count.setFont(new java.awt.Font("AdvertisingBold", 0, 12)); // NOI18N
        Count.setText("العدد ");

        Model.setFont(new java.awt.Font("AdvertisingBold", 0, 12)); // NOI18N
        Model.setText("الموديل");

        SerNum.setFont(new java.awt.Font("AdvertisingBold", 0, 12)); // NOI18N
        SerNum.setText("الرقم التسلسلي");

        CompN.setFont(new java.awt.Font("AdvertisingBold", 0, 12)); // NOI18N
        CompN.setText("نوع الشركة");

        other.setFont(new java.awt.Font("AdvertisingBold", 0, 12)); // NOI18N
        other.setText("اخرى");

        SerNum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SerNum2ActionPerformed(evt);
            }
        });

        SaveExp2.setBackground(new java.awt.Color(102, 204, 255));
        SaveExp2.setFont(new java.awt.Font("AdvertisingBold", 0, 11)); // NOI18N
        SaveExp2.setText("حفظ");
        SaveExp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveExp2ActionPerformed(evt);
            }
        });

        cancelExp2.setBackground(new java.awt.Color(102, 204, 255));
        cancelExp2.setFont(new java.awt.Font("AdvertisingBold", 0, 11)); // NOI18N
        cancelExp2.setText("الغاء");
        cancelExp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelExp2ActionPerformed(evt);
            }
        });

        Name.setFont(new java.awt.Font("AdvertisingBold", 0, 12)); // NOI18N
        Name.setText("الاسم");

        javax.swing.GroupLayout navExpensesِAddLayout = new javax.swing.GroupLayout(navExpensesِAdd);
        navExpensesِAdd.setLayout(navExpensesِAddLayout);
        navExpensesِAddLayout.setHorizontalGroup(
            navExpensesِAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navExpensesِAddLayout.createSequentialGroup()
                .addContainerGap(386, Short.MAX_VALUE)
                .addGroup(navExpensesِAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navExpensesِAddLayout.createSequentialGroup()
                        .addGroup(navExpensesِAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SerNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MissionE2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CompN2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Count2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Model2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Name2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(navExpensesِAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Count)
                            .addComponent(SerNum)
                            .addComponent(Model)
                            .addComponent(CompN)
                            .addComponent(other)
                            .addComponent(Name))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navExpensesِAddLayout.createSequentialGroup()
                        .addComponent(cancelExp2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SaveExp2)
                        .addGap(135, 135, 135))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navExpensesِAddLayout.createSequentialGroup()
                        .addComponent(title)
                        .addGap(145, 145, 145))))
        );
        navExpensesِAddLayout.setVerticalGroup(
            navExpensesِAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navExpensesِAddLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(title)
                .addGroup(navExpensesِAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(navExpensesِAddLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(Name))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navExpensesِAddLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Name2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(navExpensesِAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Count)
                    .addComponent(Count2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(navExpensesِAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Model)
                    .addComponent(Model2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(navExpensesِAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SerNum)
                    .addComponent(SerNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(navExpensesِAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CompN)
                    .addComponent(CompN2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(navExpensesِAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(other)
                    .addComponent(MissionE2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(navExpensesِAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelExp2)
                    .addComponent(SaveExp2))
                .addContainerGap(307, Short.MAX_VALUE))
        );

        nav2.add(navExpensesِAdd, "card2");

        navExpensesِ.setBackground(new java.awt.Color(255, 255, 255));

        ExpShow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ExpShow.setFont(new java.awt.Font("AdvertisingBold", 0, 12)); // NOI18N
        ExpShow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "العدد"},
                {null, "الموديل"},
                {null, "نوع الشركة"},
                {null, "الرقم التسلسلي"},
                {null, "اخرى"}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        ExpShow.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ExpShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExpShowMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ExpShow);

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archive/logo.png"))); // NOI18N

        jLabel30.setFont(new java.awt.Font("AdvertisingBold", 0, 12)); // NOI18N
        jLabel30.setText("ادارة التعليم بمحافظة عفيف - قسم تقنية المعلومات");

        jLabel31.setFont(new java.awt.Font("AdvertisingBold", 0, 11)); // NOI18N
        jLabel31.setText("إستعلام عن المصروفات");

        jButton4.setBackground(new java.awt.Color(102, 204, 255));
        jButton4.setFont(new java.awt.Font("AdvertisingBold", 0, 11)); // NOI18N
        jButton4.setText("طباعة");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        cancelExp3.setBackground(new java.awt.Color(102, 204, 255));
        cancelExp3.setFont(new java.awt.Font("AdvertisingBold", 0, 11)); // NOI18N
        cancelExp3.setText("رجوع");
        cancelExp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelExp3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navExpensesِLayout = new javax.swing.GroupLayout(navExpensesِ);
        navExpensesِ.setLayout(navExpensesِLayout);
        navExpensesِLayout.setHorizontalGroup(
            navExpensesِLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navExpensesِLayout.createSequentialGroup()
                .addGap(0, 412, Short.MAX_VALUE)
                .addGroup(navExpensesِLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navExpensesِLayout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addGap(78, 78, 78))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navExpensesِLayout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addGap(146, 146, 146))))
            .addGroup(navExpensesِLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(navExpensesِLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(navExpensesِLayout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelExp3)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navExpensesِLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel29)
                .addGap(110, 110, 110))
        );
        navExpensesِLayout.setVerticalGroup(
            navExpensesِLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navExpensesِLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addGap(18, 18, 18)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(navExpensesِLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelExp3)
                    .addComponent(jButton4))
                .addContainerGap(194, Short.MAX_VALUE))
        );

        nav2.add(navExpensesِ, "card2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(nav2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nav1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nav1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(nav2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelExp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelExp3ActionPerformed
        // TODO add your handling code here:
        nav2.removeAll();
        nav2.repaint();
        nav2.revalidate();
        //adding panel
        nav2.add(navExpansesH);
        nav2.repaint();
        nav2.revalidate();
    }//GEN-LAST:event_cancelExp3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        MessageFormat header = new MessageFormat ("heade.png");
        MessageFormat footer = new MessageFormat("report frint");
        try {
            ExpShow.print(JTable.PrintMode.NORMAL, header, footer);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("cannot print %s%n", e.getMessage());
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void ExpShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExpShowMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_ExpShowMouseClicked

    private void cancelExp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelExp2ActionPerformed
        // TODO add your handling code here:
        //remove panel
        nav2.removeAll();
        nav2.repaint();
        nav2.revalidate();
        //adding panel
        nav2.add(navExpansesH);
        nav2.repaint();
        nav2.revalidate();
    }//GEN-LAST:event_cancelExp2ActionPerformed

    private void SaveExp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveExp2ActionPerformed
        // TODO add your handling code here:

        Expensses exp = new Expensses();
        exp.setName(Name2.getText());
        exp.setNumber(Count2.getText());
        exp.setModel(Model2.getText());
        exp.setSerial(SerNum2.getText());
        exp.setCompany(CompN2.getText());
        exp.setOther(MissionE2.getText());

        data.AddExp(exp);

        Name2.setText("");
        Count2.setText("");
        Model2.setText("");
        SerNum2.setText("");
        CompN2.setText("");
        MissionE2.setText("");

        data = new DataBaseManger();

        DefaultTableModel Emodel = new DefaultTableModel() {

            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
                return false;
            }
        };
        ExpensesTable.setModel(Emodel);

        // Create a couple of columns
        Emodel.addColumn("الشركة ");
        Emodel.addColumn("الاسم");

        for (int i = 0; i < data.getExpSize(); i++) {
            Emodel.addRow(new Object[] {data.getExp(i).getCompany() , data.getExp(i).getName()});

        }

        DefaultTableCellRenderer renderer = (DefaultTableCellRenderer) ExpensesTable.getTableHeader().getDefaultRenderer();
        renderer.setHorizontalAlignment(0);

        for(int i = 0; i < 2; i++){

            DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
            rightRenderer.setHorizontalAlignment(SwingConstants.RIGHT);
            ExpensesTable.getColumnModel().getColumn(i).setCellRenderer(rightRenderer);

            nav2.removeAll();
            nav2.repaint();
            nav2.revalidate();
            //adding panel
            nav2.add(navExpansesH);
            nav2.repaint();
            nav2.revalidate();

        }

    }//GEN-LAST:event_SaveExp2ActionPerformed

    private void SerNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SerNum2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SerNum2ActionPerformed

    private void cancelExp4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelExp4ActionPerformed
        // TODO add your handling code here:
        //remove panel
        nav2.removeAll();
        nav2.repaint();
        nav2.revalidate();
        //adding panel
        nav2.add(navEmployeeH);
        nav2.repaint();
        nav2.revalidate();
    }//GEN-LAST:event_cancelExp4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton3ActionPerformed

    private void cancelEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelEmpActionPerformed
        // TODO add your handling code here:
        //remove panel
        nav2.removeAll();
        nav2.repaint();
        nav2.revalidate();
        //adding panel
        nav2.add(navEmployeeH);
        nav2.repaint();
        nav2.revalidate();

    }//GEN-LAST:event_cancelEmpActionPerformed

    private void SaveEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveEmpActionPerformed
        // TODO add your handling code here:

        EMP_INFO emp = new EMP_INFO();
        emp.setName(NameE.getText());
        emp.setID(Integer.parseInt(RegiE.getText()));
        emp.setEmail(EmailE.getText());
        emp.setPhone(NummberE.getText());
        emp.setSection(MissionE.getText());
        emp.setJob(PerfE.getText());
        emp.setSuccess(Double.parseDouble(ExecE.getText()));
        emp.setPassWord(Password.getText());

        data.AddUser(emp);

        NameE.setText("");
        RegiE.setText("");
        EmailE.setText("");
        NummberE.setText("");
        MissionE.setText("");
        PerfE.setText("");
        ExecE.setText("");
        Password.setText("");

        data = new DataBaseManger();

        DefaultTableModel model = new DefaultTableModel() {

            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
                return false;
            }
        };
        EmpTable.setModel(model);

        // Create a couple of columns
        model.addColumn("PHONE");
        model.addColumn("ID");
        model.addColumn("NAME");

        for (int i = 0; i < data.getSize(); i++) {
            // Append a row
            model.addRow(new Object[]{data.getinfo(i).getPhone(), data.getinfo(i).getID() , data.getinfo(i).getName()});

        }

        for(int i = 0; i< EmpTable.getColumnCount(); i++){

            DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
            rightRenderer.setHorizontalAlignment(SwingConstants.RIGHT);
            EmpTable.getColumnModel().getColumn(i).setCellRenderer(rightRenderer);
        }

        DefaultTableCellRenderer renderer = (DefaultTableCellRenderer) EmpTable.getTableHeader().getDefaultRenderer();
        renderer.setHorizontalAlignment(0);

        nav2.removeAll();
        nav2.repaint();
        nav2.revalidate();
        //adding panel
        nav2.add(navEmployeeH);
        nav2.repaint();
        nav2.revalidate();

    }//GEN-LAST:event_SaveEmpActionPerformed

    private void NameEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameEActionPerformed

    private void norbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_norbuttonActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Desktop.getDesktop().browse(new URL ("https://noor.moe.gov.sa/Noor/login.aspx").toURI());
        } catch (MalformedURLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        } catch (URISyntaxException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_norbuttonActionPerformed

    private void moebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moebuttonActionPerformed
        // TODO add your handling code here:

        try {
            // TODO add your handling code here:
            Desktop.getDesktop().browse(new URL ("https://www.moe.gov.sa/ar/pages/login.aspx").toURI());
        } catch (MalformedURLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        } catch (URISyntaxException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_moebuttonActionPerformed

    private void farsbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_farsbuttonActionPerformed
        try {
            // TODO add your handling code here:
            Desktop.getDesktop().browse(new URL ("https://sshr-dr.moe.sa").toURI());
        } catch (MalformedURLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        } catch (URISyntaxException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_farsbuttonActionPerformed

    private void EmpTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmpTableMouseClicked
        // TODO add your handling code here:

        JTable target = (JTable)evt.getSource();
        int column = target.getSelectedRow();
        System.out.println(column);

        nav2.removeAll();
        nav2.repaint();
        nav2.revalidate();
        //adding panel
        nav2.add(navEmployee);
        nav2.repaint();
        nav2.revalidate();

        DefaultTableCellRenderer renderer = (DefaultTableCellRenderer) target.getTableHeader().getDefaultRenderer();
        renderer.setHorizontalAlignment(0);

        DefaultTableModel Emodel = new DefaultTableModel() {

            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
                return false;
            }
        };
        EmpInfo.setModel(Emodel);

        // Create a couple of columns
        Emodel.addColumn("معلومات الموظف");
        Emodel.addColumn("الجدول");

        Emodel.addRow(new Object[] {data.getinfo(column).getName()      , "الاسم"});
        Emodel.addRow(new Object[] {data.getinfo(column).getID()        , "الهوية"});
        Emodel.addRow(new Object[] {data.getinfo(column).getPhone()     , "رقم الجوال"});
        Emodel.addRow(new Object[] {data.getinfo(column).getJob()       , "المسمى الوظيفي"});
        Emodel.addRow(new Object[] {data.getinfo(column).getSection()   , "القسم"});
        Emodel.addRow(new Object[] {data.getinfo(column).getSuccess()   , "الاداء الوظيفي"});
        Emodel.addRow(new Object[] {data.getinfo(column).getEmail()     , "البريد الالكتروني "});

        for(int i = 0; i < 2; i++){

            DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
            rightRenderer.setHorizontalAlignment(SwingConstants.RIGHT);
            EmpInfo.getColumnModel().getColumn(i).setCellRenderer(rightRenderer);

        }

    }//GEN-LAST:event_EmpTableMouseClicked

    private void EmpAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpAddActionPerformed
        // TODO add your handling code here:
        //remove panel
        nav2.removeAll();
        nav2.repaint();
        nav2.revalidate();
        //adding panel
        nav2.add(navEmployeeAdd);
        nav2.repaint();
        nav2.revalidate();
    }//GEN-LAST:event_EmpAddActionPerformed

    private void ExpensesTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExpensesTableMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:\

        JTable target = (JTable)evt.getSource();
        int column = target.getSelectedRow();

        DefaultTableModel Emodel = new DefaultTableModel() {

            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
                return false;
            }
        };
        ExpShow.setModel(Emodel);

        // Create a couple of columns
        Emodel.addColumn("البيانات");
        Emodel.addColumn("الجدول");

        Emodel.addRow(new Object[] {data.getExp(column).getName() , "الاسم"});
        Emodel.addRow(new Object[] {data.getExp(column).getNumber() , "العدد"});
        Emodel.addRow(new Object[] {data.getExp(column).getModel() , "الموديل"});
        Emodel.addRow(new Object[] {data.getExp(column).getCompany() , "نوع الشركة"});
        Emodel.addRow(new Object[] {data.getExp(column).getSerial() , "الرقم التسلسلي"});
        Emodel.addRow(new Object[] {data.getExp(column).getOther(), "اخرى"});

        for (int i = 0; i < data.getExpSize(); i++) {

            DefaultTableCellRenderer renderer = (DefaultTableCellRenderer) ExpShow.getTableHeader().getDefaultRenderer();
            renderer.setHorizontalAlignment(0);
        }

        for(int i = 0; i < 2; i++){

            DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
            rightRenderer.setHorizontalAlignment(SwingConstants.RIGHT);
            ExpShow.getColumnModel().getColumn(i).setCellRenderer(rightRenderer);

        }

        //remove panel
        nav2.removeAll();
        nav2.repaint();
        nav2.revalidate();
        //adding panel
        nav2.add(navExpensesِ);
        nav2.repaint();
        nav2.revalidate();
    }//GEN-LAST:event_ExpensesTableMouseClicked

    private void ExpAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpAdd1ActionPerformed
        // TODO add your handling code here:
        //remove panel
        nav2.removeAll();
        nav2.repaint();
        nav2.revalidate();
        //adding panel
        nav2.add(navExpensesِAdd);
        nav2.repaint();
        nav2.revalidate();
    }//GEN-LAST:event_ExpAdd1ActionPerformed

    private void progzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_progzActionPerformed
        // TODO add your handling code here:
        //remove panel
        nav2.removeAll();
        nav2.repaint();
        nav2.revalidate();
        //adding panel
        nav2.add(navProgz);
        nav2.repaint();
        nav2.revalidate();
    }//GEN-LAST:event_progzActionPerformed

    private void expensesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expensesActionPerformed
        // TODO add your handling code here:
        //remove panel
        nav2.removeAll();
        nav2.repaint();
        nav2.revalidate();
        //adding panel
        nav2.add(navExpansesH);
        nav2.repaint();
        nav2.revalidate();
    }//GEN-LAST:event_expensesActionPerformed

    private void employeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeActionPerformed
        // TODO add your handling code here:
        //remove panel
        nav2.removeAll();
        nav2.repaint();
        nav2.revalidate();
        //adding panel
        nav2.add(navEmployeeH);
        nav2.repaint();
        nav2.revalidate();
    }//GEN-LAST:event_employeeActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        //remove panel
        nav2.removeAll();
        nav2.repaint();
        nav2.revalidate();
        //adding panel
        nav2.add(navHome1);
        nav2.repaint();
        nav2.revalidate();
    }//GEN-LAST:event_homeActionPerformed

    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CompN;
    private javax.swing.JTextField CompN2;
    private javax.swing.JLabel Count;
    private javax.swing.JTextField Count2;
    private javax.swing.JTextField EmailE;
    private javax.swing.JButton EmpAdd;
    private javax.swing.JTable EmpInfo;
    private javax.swing.JTable EmpTable;
    private javax.swing.JTextField ExecE;
    private javax.swing.JButton ExpAdd1;
    private javax.swing.JTable ExpShow;
    private javax.swing.JTable ExpensesTable;
    private javax.swing.JTextField MissionE;
    private javax.swing.JTextField MissionE2;
    private javax.swing.JLabel Model;
    private javax.swing.JTextField Model2;
    private javax.swing.JLabel Name;
    private javax.swing.JTextField Name2;
    private javax.swing.JTextField NameE;
    private javax.swing.JTextField NummberE;
    private javax.swing.JTextField Password;
    private javax.swing.JTextField PerfE;
    private javax.swing.JTextField RegiE;
    private javax.swing.JButton SaveEmp;
    private javax.swing.JButton SaveExp2;
    private javax.swing.JLabel SerNum;
    private javax.swing.JTextField SerNum2;
    private javax.swing.JButton cancelEmp;
    private javax.swing.JButton cancelExp2;
    private javax.swing.JButton cancelExp3;
    private javax.swing.JButton cancelExp4;
    private javax.swing.JButton employee;
    private javax.swing.JButton expenses;
    private javax.swing.JButton farsbutton;
    private javax.swing.JButton home;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel logo;
    private javax.swing.JButton moebutton;
    private javax.swing.JPanel nav1;
    private javax.swing.JPanel nav2;
    private javax.swing.JLabel navEmpHead;
    private javax.swing.JPanel navEmployee;
    private javax.swing.JPanel navEmployeeAdd;
    private javax.swing.JPanel navEmployeeH;
    private javax.swing.JPanel navExpansesH;
    private javax.swing.JPanel navExpensesH1;
    private javax.swing.JPanel navExpensesِ;
    private javax.swing.JPanel navExpensesِAdd;
    private javax.swing.JPanel navHome1;
    private javax.swing.JPanel navProgz;
    private javax.swing.JButton norbutton;
    private javax.swing.JLabel other;
    private javax.swing.JButton progz;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
